
import React, { useState, useEffect } from 'react';

interface DemoModalProps {
  isOpen: boolean;
  onClose: () => void;
  onTryNow: () => void;
}

const DemoModal: React.FC<DemoModalProps> = ({ isOpen, onClose, onTryNow }) => {
  const [step, setStep] = useState(0);
  const [logs, setLogs] = useState<string[]>([]);

  const guideMessages = [
    "First, you select your media. Our system accepts any photo, video, or voice recording.",
    "Our AI scans the image for 'glitches' in skin, eyes, and lighting that humans can't see.",
    "For video, we check if the movement is smooth and natural or 'jittery' like a deepfake.",
    "We listen for hidden robotic patterns in the voice that reveal if the audio was generated by AI.",
    "Finally, we give you a clear 'REAL' or 'FAKE' verdict with a detailed breakdown of what we found."
  ];

  const logSequence = [
    "> Handshaking with Forensic Gateway...",
    "> Neural Engine v4.5 initialized.",
    "> Analyzing Pixel-Level Frequency...",
    "> Checking Biometric Consistency...",
    "> Scanning Temporal Artifacts...",
    "> Spectral Analysis Complete...",
    "> Cross-referencing known synthetic models...",
    "> Generating Forensic Verdict..."
  ];

  useEffect(() => {
    if (!isOpen) {
      setStep(0);
      setLogs([]);
      return;
    }

    const timer = setInterval(() => {
      setStep((prev) => (prev === 4 ? 0 : prev + 1));
    }, 5500);

    let logIdx = 0;
    const logInterval = setInterval(() => {
      if (logIdx < logSequence.length) {
        setLogs(prev => [...prev.slice(-4), logSequence[logIdx]]);
        logIdx++;
      }
    }, 1800);

    return () => {
      clearInterval(timer);
      clearInterval(logInterval);
    };
  }, [isOpen]);

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-[2000] flex items-center justify-center p-4">
      <div className="absolute inset-0 bg-black/80 backdrop-blur-2xl" onClick={onClose} />
      
      <div className="relative w-full max-w-6xl glass rounded-[3rem] border-glass shadow-2xl overflow-hidden animate-zoomIn flex flex-col" style={{ backgroundColor: 'var(--bg)', color: 'var(--text)' }}>
        
        {/* Top Header */}
        <div className="flex justify-between items-center p-6 md:p-8 border-b border-glass">
          <div className="flex items-center gap-6">
            <button 
              onClick={onClose} 
              className="flex items-center gap-2 text-xs font-black uppercase tracking-widest opacity-40 hover:opacity-100 transition-all group"
            >
              <svg className="w-4 h-4 group-hover:-translate-x-1 transition-transform" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M10 19l-7-7m0 0l7-7m-7 7h18" /></svg>
              Back
            </button>
            <div className="h-8 w-[1px] bg-glass-border hidden sm:block" />
            <div>
              <div className="flex items-center gap-3">
                <div className="w-3 h-3 rounded-full bg-primary animate-pulse shadow-[0_0_10px_var(--primary)]" />
                <h2 className="text-xl md:text-2xl font-black tracking-tighter uppercase">System <span className="text-primary italic">Demo</span></h2>
              </div>
            </div>
          </div>
          <button onClick={onClose} className="w-12 h-12 rounded-2xl glass border-glass flex items-center justify-center opacity-40 hover:opacity-100 hover:border-primary/50 transition-all">
            <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" /></svg>
          </button>
        </div>

        <div className="flex flex-col lg:flex-row flex-1 p-4 md:p-6 gap-6 min-h-0 overflow-hidden">
          
          {/* Main Visual Demo Area */}
          <div className="flex-[3] bg-black/5 rounded-[2rem] overflow-hidden relative border border-glass shadow-inner min-h-[300px] lg:min-h-0">
            
            {/* Guide Text Overlay */}
            <div className="absolute top-0 left-0 right-0 z-30 p-6 md:p-8 bg-gradient-to-b from-[var(--bg)] via-[var(--bg)]/90 to-transparent">
               <div className="max-w-2xl">
                  <span className="inline-block px-3 py-1 rounded-full bg-primary text-white text-[10px] font-black uppercase tracking-widest mb-3 shadow-lg shadow-primary/20">
                    Step {step + 1}: {demoSteps[step].title}
                  </span>
                  <p className="text-xl md:text-3xl font-bold leading-tight animate-slideDown" style={{ color: 'var(--text)' }}>
                    {guideMessages[step]}
                  </p>
               </div>
            </div>

            {/* Simulated Content */}
            <div className="absolute inset-0 flex items-center justify-center">
              {step === 0 && (
                <div className="flex flex-col items-center justify-center animate-fadeIn p-12">
                  <div className="w-full max-w-sm glass rounded-[2.5rem] border-dashed border-2 border-glass p-12 flex flex-col items-center text-center">
                    <div className="w-20 h-20 rounded-full bg-primary/10 flex items-center justify-center mb-6 animate-bounce">
                      <svg className="w-10 h-10 text-primary" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M7 16a4 4 0 01-.88-7.903A5 5 0 1115.9 6L16 6a5 5 0 011 9.9M15 13l-3-3m0 0l-3 3m3-3v12" /></svg>
                    </div>
                    <div className="space-y-4">
                       <div className="px-8 py-3 bg-primary rounded-xl text-white font-black text-xs uppercase shadow-xl shadow-primary/20">Choose File</div>
                       <p className="opacity-30 text-[10px] font-mono tracking-widest uppercase">Accepting Multi-Modal Buffers</p>
                    </div>
                  </div>
                </div>
              )}

              {step === 1 && (
                <div className="w-full h-full relative animate-fadeIn overflow-hidden">
                  <img src="https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=1200" className="w-full h-full object-cover grayscale opacity-40" />
                  <div className="absolute inset-0 flex items-center justify-center">
                    <div className="relative w-64 h-64 border-2 border-primary/50 rounded-full animate-pulse flex items-center justify-center">
                       <div className="absolute inset-0 border border-primary/20 rounded-full animate-spin-slow" />
                       <div className="w-3 h-3 bg-red-500 rounded-full shadow-[0_0_20px_red] z-10" />
                       <div className="absolute top-1/2 left-1/2 w-[200px] h-[1px] bg-red-500/50 origin-left animate-spin" />
                    </div>
                  </div>
                  <div className="scan-line" />
                </div>
              )}

              {step === 2 && (
                <div className="w-full h-full flex items-center justify-center bg-black/10 gap-4 p-12 animate-fadeIn overflow-hidden">
                  {[1, 2, 3, 4, 5].map(i => (
                    <div key={i} className={`flex-shrink-0 w-32 h-48 rounded-2xl overflow-hidden border-2 transition-all duration-1000 ${i === 3 ? 'border-primary scale-125 z-10 shadow-2xl' : 'border-glass opacity-20'}`}>
                      <img src={`https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=300&sig=${i}`} className="w-full h-full object-cover" />
                    </div>
                  ))}
                  <div className="absolute bottom-10 left-1/2 -translate-x-1/2 px-4 py-1 glass rounded-full border-primary/30">
                    <span className="text-[10px] font-mono font-bold text-primary animate-pulse uppercase tracking-[0.3em]">Temporal Delta Detected</span>
                  </div>
                </div>
              )}

              {step === 3 && (
                <div className="w-full h-full flex flex-col items-center justify-center bg-black/5 animate-fadeIn p-12">
                  <div className="flex items-center gap-2 h-32 mb-8">
                    {[...Array(30)].map((_, i) => (
                      <div 
                        key={i} 
                        className="w-2 rounded-full bg-primary/40 animate-wave" 
                        style={{ height: `${20 + Math.random() * 80}%`, animationDelay: `${i * 0.05}s` }} 
                      />
                    ))}
                  </div>
                  <div className="px-6 py-2 glass rounded-full border-primary/20 text-primary font-mono text-xs font-bold uppercase tracking-widest">Spectral Pattern Match: AI-VOX</div>
                </div>
              )}

              {step === 4 && (
                <div className="w-full h-full flex flex-col items-center justify-center p-12 animate-fadeIn relative overflow-hidden">
                   <div className="absolute inset-0 opacity-[0.03] pointer-events-none rotate-12 scale-150 bg-[repeating-linear-gradient(45deg,transparent,transparent_20px,var(--primary)_20px,var(--primary)_40px)]" />
                   
                   <div className="glass p-12 rounded-[3rem] border-red-500/30 bg-red-500/5 text-center shadow-2xl relative z-10">
                      <p className="text-red-500 text-sm font-black uppercase tracking-[0.4em] mb-4">Forensic Results</p>
                      <h3 className="text-7xl md:text-9xl font-black text-red-500 italic mb-8 drop-shadow-2xl">FAKE</h3>
                      <div className="flex justify-center gap-12">
                         <div className="text-left">
                            <p className="opacity-40 text-[10px] uppercase font-black tracking-widest mb-1">Confidence</p>
                            <p className="text-3xl font-black">99.8%</p>
                         </div>
                         <div className="text-left">
                            <p className="opacity-40 text-[10px] uppercase font-black tracking-widest mb-1">Source</p>
                            <p className="text-3xl font-black text-primary">SYNTHETIC</p>
                         </div>
                      </div>
                   </div>
                </div>
              )}
            </div>

            {/* Bottom Controls Overlay */}
            <div className="absolute bottom-6 left-6 right-6 flex justify-between items-center z-20">
              <div className="flex gap-3">
                 {[0, 1, 2, 3, 4].map((i) => (
                   <div key={i} className={`h-1.5 rounded-full transition-all duration-700 ${step === i ? 'w-16 bg-primary shadow-[0_0_15px_var(--primary)]' : 'w-4 bg-glass-border'}`} />
                 ))}
              </div>
              <div className="glass px-5 py-2 rounded-full border-glass flex items-center gap-3">
                <div className="w-2 h-2 rounded-full bg-green-500 animate-pulse" />
                <span className="text-[10px] font-mono opacity-50 uppercase tracking-widest font-black">Forensic Core v4.5</span>
              </div>
            </div>
          </div>

          {/* Sidebar - Stages Summary */}
          <div className="w-full lg:w-80 flex flex-col gap-5">
            <div className="flex-1 glass p-8 rounded-[2.5rem] border-glass bg-black/5 flex flex-col">
              <h4 className="font-black text-xs uppercase tracking-widest mb-6 opacity-60 border-b border-glass pb-4">Analysis Stages</h4>
              <div className="space-y-6 flex-1">
                {demoSteps.map((s, i) => (
                  <div key={i} className={`flex items-start gap-4 transition-all duration-500 ${step === i ? 'translate-x-3' : 'opacity-20'}`}>
                    <div className={`w-8 h-8 rounded-xl flex items-center justify-center font-black text-xs shadow-lg transition-colors ${step === i ? 'bg-primary text-white' : 'bg-glass-border'}`}>
                      {i + 1}
                    </div>
                    <div>
                      <p className={`text-xs font-bold uppercase tracking-tight ${step === i ? 'text-primary' : ''}`}>{s.title}</p>
                      <p className="text-[10px] opacity-50 mt-1 leading-tight">{s.shortDesc}</p>
                    </div>
                  </div>
                ))}
              </div>
              
              {/* Try it by your own link */}
              <div className="mt-8 p-4 glass rounded-2xl border-primary/20 bg-primary/5 text-center group cursor-pointer hover:border-primary/50 transition-all" onClick={onTryNow}>
                <p className="text-[10px] font-black uppercase text-primary mb-1">Ready to test?</p>
                <p className="text-xs font-bold group-hover:underline">TRY BY YOUR OWN ➔</p>
              </div>
            </div>

            <div className="glass p-6 rounded-[2rem] border-primary/20 bg-primary/5">
               <p className="text-[10px] font-black text-primary mb-2 uppercase tracking-widest">Global Support</p>
               <p className="text-xs leading-relaxed opacity-70">
                 Works on any device. Start protecting your digital integrity today.
               </p>
            </div>
          </div>
        </div>

        {/* Action Footer */}
        <div className="px-8 py-8 md:px-10 md:py-10 flex flex-col sm:flex-row gap-4 border-t border-glass bg-black/5">
          <button 
            onClick={onTryNow}
            className="flex-[2] py-6 rounded-[2.5rem] bg-primary text-white font-black text-xl hover:scale-[1.02] active:scale-95 transition-all shadow-2xl shadow-primary/30 flex items-center justify-center gap-4 group italic tracking-tighter"
          >
            I'M READY TO ANALYZE
            <svg className="w-7 h-7 group-hover:translate-x-2 transition-transform" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M17 8l4 4m0 0l-4 4m4-4H3" /></svg>
          </button>
          <button 
            onClick={() => { setStep(0); setLogs([]); }}
            className="flex-1 py-6 rounded-[2.5rem] glass border-glass font-black hover:bg-black/10 transition-all flex items-center justify-center gap-4 tracking-tighter"
          >
            WATCH AGAIN
          </button>
        </div>
      </div>

      <style>{`
        @keyframes wave {
          0%, 100% { transform: scaleY(0.4); opacity: 0.3; }
          50% { transform: scaleY(1); opacity: 1; }
        }
        .animate-wave {
          animation: wave 1s ease-in-out infinite;
          transform-origin: center;
        }
        .animate-fadeIn { animation: fadeIn 0.4s ease-out forwards; }
        .animate-slideDown { 
          opacity: 0;
          transform: translateY(-20px);
          animation: slideDown 0.6s cubic-bezier(0.2, 0.8, 0.2, 1) forwards; 
        }
        @keyframes fadeIn { from { opacity: 0; } to { opacity: 1; } }
        @keyframes slideDown { from { opacity: 0; transform: translateY(-20px); } to { opacity: 1; transform: translateY(0); } }
        .animate-spin-slow { animation: spin 15s linear infinite; }
        @keyframes spin { from { transform: rotate(0deg); } to { transform: rotate(360deg); } }
      `}</style>
    </div>
  );
};

const demoSteps = [
  { title: "Select Media", shortDesc: "Photos, Videos, or Voice clips" },
  { title: "Neural Scan", shortDesc: "Scanning invisible pixels" },
  { title: "Motion Audit", shortDesc: "Validating temporal frame data" },
  { title: "Spectral Sync", shortDesc: "AI-Vox pattern matching" },
  { title: "Final Report", shortDesc: "The ultimate forensic verdict" }
];

export default DemoModal;
